### ISSUE TITLE
Remove node modules from scss

### ISSUE THREAD

**Issue by fahimfaisaal** [Rezuan-Ahmed-git/practice-design-system-sl#1]
Mistakenly you push the node module inside the scss directory. remove this through `.gitignore` file

**Comment by Rezuan-Ahmed-git** [comment]
Thanks for pointing that out. I will remove it asap. 🤓

**Comment by Rezuan-Ahmed-git** [comment]
Problem resolved

**Comment by Rezuan-Ahmed-git** [comment]
node module is removed

**Comment by fahimfaisaal** [comment]
Great
